### ISSUE TITLE
GetSquad() is not shared

### ISSUE THREAD

**Issue by KekkyShmekky** [StyledStrike/gmod-squad-menu#2]
Hey so I'm trying to use the API as outlined in the README but I noticed that the client is not recognizing SquadMenu:GetSquad(id), which is necessary for a particular task I'm trying to do in order to get the color values of the squad. Is there another way to do this?

**Comment by StyledStrike** [comment]
Oh sorry about that, that function really only exists on the server because transmitting data about all squads to all players use a lot of bandwidth, so clients are only aware about all squads while the squad list is open.

If all you need is the color of the `LocalPlayer()`'s squad however, you can use this:

```lua
local mySquad = SquadMenu.mySquad

-- Check if the local player has a squad (is it not `nil`)
if mySquad then
    print( mySquad.color )
end
```
